version: '3'
services:
  sshd-server:
    build: .
    ports:
      - "<호스트os에서 ssh컨테이너 연결할포트>:<ssh컨테이너포트>"
  mongo-server:
    image: 'mongo:latest'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fsfsdfafs
    restart: always
    ports:
      - <호스트os에서 몽고디비컨테이너연결할 포트>:<몽고디비컨테이너포트>
    volumes:
      - mongodb_data_container:/data/db
    depends_on:
      - sshd-server
    links:
      - sshd-server
  uvicorn-server:
    build: .
    command: uvicorn project.main:app --reload --host 0.0.0.0
    volumes:
      - .:/usr/src/project
    ports:
      - "<호스트os에서 uvicorn서버컨테이너연결포트>:<uvicorn서버컨테이너포트>"
    depends_on:
      - mongo-server
    links:
      - mongo-server
    restart: always
volumes:
  mongodb_data_container:
